package setup

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// RunWizard runs an interactive setup wizard that creates ~/.marsclaw/config.yaml.
func RunWizard() error {
	home, _ := os.UserHomeDir()
	dir := filepath.Join(home, ".marsclaw")
	configPath := filepath.Join(dir, "config.yaml")

	if _, err := os.Stat(configPath); err == nil {
		fmt.Printf("Config already exists at %s\n", configPath)
		if !confirm("Overwrite?") {
			fmt.Println("Aborted.")
			return nil
		}
	}

	reader := bufio.NewReader(os.Stdin)

	fmt.Print("\n  MarsClaw Setup\n\n")

	// Provider selection.
	fmt.Println("Which LLM provider?")
	fmt.Println("  1) Anthropic (Claude)")
	fmt.Println("  2) Google Gemini (uses GCP credits)")
	fmt.Println("  3) OpenAI (GPT)")
	fmt.Println("  4) Ollama (local, free, offline)")
	provider := prompt(reader, "Choice [1]: ", "1")

	var providerName, model, envKey string
	switch provider {
	case "2":
		providerName = "gemini"
		model = prompt(reader, "Model [gemini-2.5-flash]: ", "gemini-2.5-flash")
		envKey = "GEMINI_API_KEY"
	case "3":
		providerName = "openai"
		model = prompt(reader, "Model [gpt-4o]: ", "gpt-4o")
		envKey = "OPENAI_API_KEY"
	case "4":
		providerName = "ollama"
		model = prompt(reader, "Model [llama3.1]: ", "llama3.1")
	default:
		providerName = "anthropic"
		model = prompt(reader, "Model [claude-sonnet-4-20250514]: ", "claude-sonnet-4-20250514")
		envKey = "ANTHROPIC_API_KEY"
	}

	// Budget.
	budget := prompt(reader, "Daily budget in USD (0 = unlimited) [0]: ", "0")

	// Security.
	strict := prompt(reader, "Require approval for dangerous tools? [y/N]: ", "n")

	// Build config.
	var b strings.Builder
	b.WriteString("# MarsClaw configuration\n")
	b.WriteString("# Generated by: marsclaw init\n\n")
	b.WriteString("providers:\n")
	b.WriteString(fmt.Sprintf("  default: %s\n", providerName))

	switch providerName {
	case "anthropic":
		b.WriteString("  anthropic:\n")
		b.WriteString(fmt.Sprintf("    api_key_env: %s\n", envKey))
		b.WriteString(fmt.Sprintf("    default_model: %s\n", model))
	case "gemini":
		b.WriteString("  gemini:\n")
		b.WriteString(fmt.Sprintf("    api_key_env: %s\n", envKey))
		b.WriteString(fmt.Sprintf("    default_model: %s\n", model))
	case "openai":
		b.WriteString("  openai:\n")
		b.WriteString(fmt.Sprintf("    api_key_env: %s\n", envKey))
		b.WriteString(fmt.Sprintf("    default_model: %s\n", model))
	case "ollama":
		b.WriteString("  ollama:\n")
		b.WriteString(fmt.Sprintf("    default_model: %s\n", model))
	}

	b.WriteString("\nagent:\n")
	b.WriteString("  max_turns: 25\n")
	b.WriteString("  enable_streaming: true\n")

	b.WriteString("\ncost:\n")
	b.WriteString("  inline_display: true\n")
	b.WriteString(fmt.Sprintf("  daily_budget: %s\n", budget))

	b.WriteString("\nsecurity:\n")
	if strings.EqualFold(strict, "y") || strings.EqualFold(strict, "yes") {
		b.WriteString("  strict_approval: true\n")
	} else {
		b.WriteString("  strict_approval: false\n")
	}
	b.WriteString("  scan_credentials: true\n")
	b.WriteString("  path_traversal_guard: true\n")

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	if err := os.WriteFile(configPath, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	fmt.Printf("\nConfig saved to %s\n", configPath)

	if envKey != "" {
		val := os.Getenv(envKey)
		if val == "" {
			fmt.Printf("\nRemember to set your API key:\n  export %s=\"your-key-here\"\n", envKey)
		} else {
			fmt.Printf("\n%s is set. You're ready to go!\n", envKey)
		}
	}

	fmt.Println("\nRun 'marsclaw' to start chatting.")
	return nil
}

func prompt(reader *bufio.Reader, label, defaultVal string) string {
	fmt.Print(label)
	line, _ := reader.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return defaultVal
	}
	return line
}

func confirm(question string) bool {
	reader := bufio.NewReader(os.Stdin)
	fmt.Printf("%s [y/N] ", question)
	line, _ := reader.ReadString('\n')
	line = strings.TrimSpace(strings.ToLower(line))
	return line == "y" || line == "yes"
}
